//
//  RegisterPresenter.swift
//  Arquiteturas
//
//  Created by Frédéric Helfer on 01/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPresentationLogic
{
    func presentSomething(response: Register.Something.Response)
    func presentError(error: Register.Something.ViewError)
}

class RegisterPresenter: RegisterPresentationLogic
{
    weak var viewController: RegisterDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Register.Something.Response)
    {
        let viewModel = Register.Something.ViewModel(userModel: response.userModel)
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentError(error: Register.Something.ViewError) {
        let viewError = Register.Something.ViewError(error: error.error)
        viewController?.displayError(error: viewError)
    }
}
