//
//  LoginViewController.swift
//  Arquiteturas
//
//  Created by Frédéric Helfer on 31/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: AnyObject
{
    func displaySomething(viewModel: Login.Something.ViewModel)
    func displayError(error: Login.Something.ViewError)
}

class LoginViewController: UIViewController, LoginDisplayLogic
{
    
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: - View lifecycle
    
    override func loadView() {
        super.loadView()
        self.view = loginView
    }
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.title = "Login"
        doSomething()
    }
    
    // MARK: - Do something
    
    private lazy var loginView: LoginView = {
        let view = LoginView(frame: .zero)
        
        view.onLoginTap = { [weak self] userModel in
            if let self {
                self.loginTap(userModel: userModel)
            }
            
        }
        
        view.onRegisterTap = { [weak self] in
            if let self {
                self.registerTap()
            }
        }
        
        return view
    }()
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
    }
    
    func displaySomething(viewModel: Login.Something.ViewModel)
    {
        router?.routeToHome()
    }
    
    func displayError(error: Login.Something.ViewError) {
        let error = error.error.localizedDescription
        let alert = UIAlertController(title: "Error", message: error, preferredStyle: .alert)
        
        alert.addAction(UIAlertAction(title: "Ok", style: .default))
        
        self.present(alert, animated: true)
    }
    
    func loginTap(userModel: UserModel) {
        let request = Login.Something.Request(userModel: userModel)
        interactor?.doSomething(request: request)
    }
    
    func registerTap() {
        router?.routeToRegister()
    }
}
