//
//  LoginWorker.swift
//  Arquiteturas
//
//  Created by Frédéric Helfer on 31/01/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
    func loginUser(userMode: UserModel,
                   successHandler: @escaping (UserModel?) -> Void,
                   failureHandler: @escaping (Error?) -> Void) {
        
        let manager = UserManager(business: UserBusiness())
        manager.login(email: userMode.email, password: userMode.password) { model in
            successHandler(model)
        } failureHandler: { error in
            failureHandler(error)
        }
        
    }
}
